"""registered -> subscribed

Revision ID: 90bbcab31129
Revises: df69bc55f844
Create Date: 2023-09-25 14:35:49.669081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90bbcab31129'
down_revision: Union[str, None] = 'df69bc55f844'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('subscribed_at', sa.TIMESTAMP(), nullable=True))
    op.drop_column('user', 'registered_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('registered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('user', 'subscribed_at')
    # ### end Alembic commands ###
