"""initial

Revision ID: df69bc55f844
Revises: 
Create Date: 2023-09-25 13:53:06.217896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df69bc55f844'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rarity',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('role',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('user',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('registered_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('roles', sa.String(), nullable=True),
    sa.Column('inventory', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('skin',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rarity_uuid', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['rarity_uuid'], ['rarity.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('inventory',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('skin_uuid', sa.Uuid(), nullable=True),
    sa.Column('added_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['skin_uuid'], ['skin.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('record',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('registered_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('skin_uuid', sa.Uuid(), nullable=True),
    sa.Column('price', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['skin_uuid'], ['skin.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record')
    op.drop_table('inventory')
    op.drop_table('skin')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('rarity')
    # ### end Alembic commands ###
